name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Git Semantic Version
        id: version
        uses: PaulHatch/semantic-version@v4.0.3
        with:
          major_pattern: "^major:"
          minor_pattern: "^feat:"
          format: "${{major}}.${{minor}}.${{patch}}"

      - name: Docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t emmanuel142/andesbike-frontend:${{ steps.version.outputs.version }} .
          docker tag emmanuel142/andesbike-frontend:${{ steps.version.outputs.version }} emmanuel142/andesbike-frontend:latest
          docker push emmanuel142/andesbike-frontend:${{ steps.version.outputs.version }}
          docker push emmanuel142/andesbike-frontend:latest
